// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:`
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiJ_NX4gibYotpfr-kiHaP7floECEFNhE',
    appId: '1:657220813318:web:dfe079eaf2d80d5484b987',
    messagingSenderId: '657220813318',
    projectId: 'spotify-clone-flutter17924',
    authDomain: 'spotify-clone-flutter17924.firebaseapp.com',
    storageBucket: 'spotify-clone-flutter17924.appspot.com',
    measurementId: 'G-8X0WV737SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlbkTPt6X3i2G3VU-L_kTjGM3580IuS-Y',
    appId: '1:657220813318:android:dca1cea5d7d1637a84b987',
    messagingSenderId: '657220813318',
    projectId: 'spotify-clone-flutter17924',
    storageBucket: 'spotify-clone-flutter17924.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtlahxRuATtt5DS3IE5YZFLEH3w6Gb6E4',
    appId: '1:657220813318:ios:eed2ebd3f80a4b0784b987',
    messagingSenderId: '657220813318',
    projectId: 'spotify-clone-flutter17924',
    storageBucket: 'spotify-clone-flutter17924.appspot.com',
    iosBundleId: 'com.example.spotifyProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtlahxRuATtt5DS3IE5YZFLEH3w6Gb6E4',
    appId: '1:657220813318:ios:eed2ebd3f80a4b0784b987',
    messagingSenderId: '657220813318',
    projectId: 'spotify-clone-flutter17924',
    storageBucket: 'spotify-clone-flutter17924.appspot.com',
    iosBundleId: 'com.example.spotifyProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiJ_NX4gibYotpfr-kiHaP7floECEFNhE',
    appId: '1:657220813318:web:e2527f8a52a1840d84b987',
    messagingSenderId: '657220813318',
    projectId: 'spotify-clone-flutter17924',
    authDomain: 'spotify-clone-flutter17924.firebaseapp.com',
    storageBucket: 'spotify-clone-flutter17924.appspot.com',
    measurementId: 'G-G6635JCMQP',
  );

}