// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:`
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKwQHecIOgsrwcHCAtbEhq5UpuScKLlpM',
    appId: '1:449533089869:web:d11e63facc593201afa404',
    messagingSenderId: '449533089869',
    projectId: 'spotify-clone-12-9',
    authDomain: 'spotify-clone-12-9.firebaseapp.com',
    storageBucket: 'spotify-clone-12-9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdW8n6xEOaapzB6XTw5SsHwx8NpaEZA6k',
    appId: '1:449533089869:android:3da26631e6f7d3fcafa404',
    messagingSenderId: '449533089869',
    projectId: 'spotify-clone-12-9',
    storageBucket: 'spotify-clone-12-9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0joPC1jTNvhcMxo14snRN8gdThREE9lQ',
    appId: '1:449533089869:ios:5ea835fe3c59375bafa404',
    messagingSenderId: '449533089869',
    projectId: 'spotify-clone-12-9',
    storageBucket: 'spotify-clone-12-9.appspot.com',
    iosBundleId: 'com.example.spotifyProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0joPC1jTNvhcMxo14snRN8gdThREE9lQ',
    appId: '1:449533089869:ios:5ea835fe3c59375bafa404',
    messagingSenderId: '449533089869',
    projectId: 'spotify-clone-12-9',
    storageBucket: 'spotify-clone-12-9.appspot.com',
    iosBundleId: 'com.example.spotifyProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKwQHecIOgsrwcHCAtbEhq5UpuScKLlpM',
    appId: '1:449533089869:web:529be91b55426e0dafa404',
    messagingSenderId: '449533089869',
    projectId: 'spotify-clone-12-9',
    authDomain: 'spotify-clone-12-9.firebaseapp.com',
    storageBucket: 'spotify-clone-12-9.appspot.com',
  );
}
